/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppCreditRouteImport } from './routes/_app.credit'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGrowthRouteImport } from './routes/_app.growth'
import { Route as AppImproveRouteImport } from './routes/_app.improve'
import { Route as AppInvestmentRouteImport } from './routes/_app.investment'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRiskRouteImport } from './routes/_app.risk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreditRoute = AppCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppImproveRoute = AppImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentRoute = AppInvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/credit': typeof AppCreditRoute
  '/dashboard': typeof AppDashboardRoute
  '/growth': typeof AppGrowthRoute
  '/improve': typeof AppImproveRoute
  '/investment': typeof AppInvestmentRoute
  '/profile': typeof AppProfileRoute
  '/risk': typeof AppRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/credit': typeof AppCreditRoute
  '/dashboard': typeof AppDashboardRoute
  '/growth': typeof AppGrowthRoute
  '/improve': typeof AppImproveRoute
  '/investment': typeof AppInvestmentRoute
  '/profile': typeof AppProfileRoute
  '/risk': typeof AppRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/_app/credit': typeof AppCreditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/growth': typeof AppGrowthRoute
  '/_app/improve': typeof AppImproveRoute
  '/_app/investment': typeof AppInvestmentRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/risk': typeof AppRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/credit'
    | '/dashboard'
    | '/growth'
    | '/improve'
    | '/investment'
    | '/profile'
    | '/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/credit'
    | '/dashboard'
    | '/growth'
    | '/improve'
    | '/investment'
    | '/profile'
    | '/risk'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/_app/credit'
    | '/_app/dashboard'
    | '/_app/growth'
    | '/_app/improve'
    | '/_app/investment'
    | '/_app/profile'
    | '/_app/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/credit': {
      id: '/_app/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof AppCreditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth': {
      id: '/_app/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/improve': {
      id: '/_app/improve'
      path: '/improve'
      fullPath: '/improve'
      preLoaderRoute: typeof AppImproveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investment': {
      id: '/_app/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof AppInvestmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreditRoute: typeof AppCreditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppImproveRoute: typeof AppImproveRoute
  AppInvestmentRoute: typeof AppInvestmentRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRiskRoute: typeof AppRiskRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreditRoute: AppCreditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppImproveRoute: AppImproveRoute,
  AppInvestmentRoute: AppInvestmentRoute,
  AppProfileRoute: AppProfileRoute,
  AppRiskRoute: AppRiskRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
